### PR TITLE
Updated to TF serving 2.4.0 final tag

### PR DESCRIPTION
**Pull request by npanpaliya**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/master/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/master/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/master/tests/) to validate this change?  

## Description

Fixes https://github.com/open-ce/open-ce/issues/226

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Review by jayfurmanek — APPROVED** [review]
Great! Thanks for working this out.

**Comment by jayfurmanek** [comment]
PR check is for build number

**Comment by npanpaliya** [comment]
> PR check is for build number

Should build number be incremented? I thought this is the real 2.4.0 update. And hence didn't update the version.

**Comment by npanpaliya** [comment]
Build on x86 is yet to be verified. I'd started the full environment build on x86 container but it failed due to some conda error. So, now I've created a new container and started all over again.

**Comment by jayfurmanek** [comment]
yeah, the PR check doesn't really understand RC versions. It just knows the recipe has changed and wants an build number update. Let's go ahead and bump up the build number.

**Comment by bnemanich** [comment]
It should be incremented whenever the build has changed for a package and the version number of the package hasn't changed. In this case, the package version was already set to 2.4, so the build number should be incremented.

**Review by jayfurmanek — APPROVED** [review]

**Comment by npanpaliya** [comment]
@jayfurmanek , @bnemanich - I've updated the patch for TF on x86 to handle that absl error.

**Pull request merged**
